import assert from "node:assert/strict";
import test from "node:test";
import { contractId, type BinaryContentSource, type ChangeCursor, type ContentHash, type MutationIntentId, type RemoteObjectId, type RemoteRevisionId, type SemanticStateGeneration, type VaultIdentity, type VaultPath } from "../../../src/contracts/common";
import type { DriveResult, ManagedRemoteIdentity } from "../../../src/contracts/google-drive";
import type { RemoteFolderCreatePhysicalMutationDescriptor } from "../../../src/contracts/synchronization-folder-create-foundation";
import type { CanonicalFileContentProof, RemoteMutationIdentity, SynchronizationCancellationSignal } from "../../../src/contracts/synchronization-foundation";
import { GoogleOAuthSession, ObsidianSecretStore } from "../../../src/drive/auth";
import { GoogleDriveAdapter } from "../../../src/drive/google-drive-port";
import { GoogleHttpTransport, type PortableRequestInit } from "../../../src/drive/transport";

class MemorySecrets { readonly values=new Map<string,string>(); getSecret(id:string){return this.values.get(id)??null;} setSecret(id:string,v:string){this.values.set(id,v);} deleteSecret(id:string){this.values.delete(id);} }
class StubTransport extends GoogleHttpTransport { constructor(private readonly handler:(url:string,init?:PortableRequestInit)=>Promise<DriveResult<Response>>){const m=new MemorySecrets();super(new GoogleOAuthSession({clientId:"c",redirectUri:"https://cb"},new ObsidianSecretStore(m)));} override request(url:string,init:PortableRequestInit={}):Promise<DriveResult<Response>>{return this.handler(url,init);} }
const ok=(body:unknown,status=200,headers:Record<string,string>={})=>Promise.resolve({ok:true,value:new Response(body===undefined?undefined:JSON.stringify(body),{status,headers:{"content-type":"application/json",...headers}})} as DriveResult<Response>);
const fail=(kind:"not-found"|"transient-failure"|"authentication-required",detail?:string)=>Promise.resolve({ok:false,signal:kind==="not-found"?{kind}:{kind,detail}} as DriveResult<Response>);
const vp=(s:string)=>contractId<"VaultPath">(s) as VaultPath;
const ro=(s:string)=>contractId<"RemoteObjectId">(s) as RemoteObjectId;
const rev=(s:string)=>contractId<"RemoteRevisionId">(s) as RemoteRevisionId;
const cur=(s:string)=>contractId<"ChangeCursor">(s) as ChangeCursor;
const intent=(s:string)=>contractId<"MutationIntentId">(s) as MutationIntentId;
const generation=(s:string)=>contractId<"SemanticStateGeneration">(s) as SemanticStateGeneration;
const vault=(s:string)=>contractId<"VaultIdentity">(s) as VaultIdentity;
const ch=(s:string)=>contractId<"ContentHash">(s) as ContentHash;
const FOLDER="application/vnd.google-apps.folder";
const root=()=>({id:"root",name:"BRAIN Sync",mimeType:FOLDER,trashed:false,appProperties:{brainSyncRole:"brain-sync-root",brainVaultIdentity:"vault-1",brainProtocolVersion:"1"}});
const content=()=>({id:"content",name:"vault",mimeType:FOLDER,parents:["root"],trashed:false,appProperties:{brainSyncRole:"brain-sync-content"}});
const config=()=>({id:"config",name:"__brain_sync_portable_config__",mimeType:FOLDER,parents:["root"],trashed:false,appProperties:{brainSyncRole:"brain-sync-portable-config"}});
const prov=(domain:"content"|"portable-config"="content")=>({brainManagedRootId:"root",brainSyncDomain:domain});
const identity:ManagedRemoteIdentity={rootId:ro("root"),vaultIdentity:vault("vault-1"),protocolVersion:contractId<"ProtocolVersion">("1")};
function adapter(handler:(url:string,init?:PortableRequestInit)=>Promise<DriveResult<Response>>){const backing=new MemorySecrets();backing.setSecret("brain-gdrive-paired-account","acct");const store=new ObsidianSecretStore(backing);return new GoogleDriveAdapter(new GoogleOAuthSession({clientId:"c",redirectUri:"https://cb"},store),new StubTransport(handler),store);}
function common(url:string):Promise<DriveResult<Response>>|undefined{const u=decodeURIComponent(url);if(u.includes("/about?"))return ok({user:{permissionId:"acct"}});if(u.includes("/files/root?"))return ok(root());if(u.includes("brainSyncRole' and value='brain-sync-content"))return ok({files:[content()]});if(u.includes("'root' in parents")&&u.includes("__brain_sync_portable_config__"))return ok({files:[config()]});return undefined;}
const cancelledSignal=(value=true):SynchronizationCancellationSignal=>({cancelled:value,onCancellation:()=>()=>{}});
const descriptor=(target="empty/remote",parent="parent") : RemoteFolderCreatePhysicalMutationDescriptor=>({kind:"remote-folder-create",targetSide:"remote",mutationKind:"create",intentId:intent("intent-folder"),targetPath:vp(target),parentRemoteObjectId:ro(parent),pathAuthority:{generation:generation("g1"),targetPath:vp(target),parentPath:vp(target.split("/").slice(0,-1).join("/")),pathComparisonKey:target.toLowerCase(),expectedTarget:"absent"},remoteMutation:{kind:"reserved-folder-create",intentId:intent("intent-folder"),reservedRemoteObjectId:ro("reserved"),path:vp(target)}});

function recoveryAdapter(options:{reserved?:unknown;reservedFailure?:"not-found"|"transient-failure";parent?:unknown;targetChildren?:unknown[];duplicateParent?:boolean;mutationCounter?:{value:number}}={}){
 return adapter(async(url,init)=>{if(init?.method&&init.method!=="GET"&&init.method!==undefined){if(options.mutationCounter)options.mutationCounter.value++;}const u=decodeURIComponent(url);const c=common(url);if(c)return c;
   if(u.includes("/files/reserved?")){if(options.reservedFailure)return fail(options.reservedFailure);return options.reserved?ok(options.reserved):fail("not-found");}
   if(u.includes("/files/parent?"))return options.parent?ok(options.parent):ok({id:"parent",name:"empty",mimeType:FOLDER,parents:["content"],trashed:false,appProperties:prov()});
   if(u.includes("brainSyncRole' and value='brain-sync-root"))return ok({files:[root()]});
   if(u.includes("'content' in parents")&&u.includes("name='empty'"))return ok({files:options.duplicateParent?[{id:"parent",name:"empty",mimeType:FOLDER,parents:["content"],trashed:false,appProperties:prov()},{id:"parent2",name:"empty",mimeType:FOLDER,parents:["content"],trashed:false,appProperties:prov()}]:[{id:"parent",name:"empty",mimeType:FOLDER,parents:["content"],trashed:false,appProperties:prov()}]});
   if(u.includes("'parent' in parents")&&u.includes("name='remote'"))return ok({files:options.targetChildren??[]});
   if(u.includes("'parent2' in parents")&&u.includes("name='remote'"))return ok({files:options.targetChildren??[]});
   throw new Error(`unhandled ${init?.method??"GET"} ${u}`);
 });
}

test("workstream A v1.2 recovery: correct reserved folder returns actual path and parent",async()=>{const a=recoveryAdapter({reserved:{id:"reserved",name:"remote",mimeType:FOLDER,parents:["parent"],trashed:false,appProperties:prov()}});const r=await a.observeFolderCreateRecovery(descriptor());assert.deepEqual(r,{status:"folder",targetPath:"empty/remote",pathComparisonKey:"empty/remote",remoteObjectId:"reserved",parentRemoteObjectId:"parent"});});
test("workstream A v1.2 recovery: wrong actual parent is not overwritten from descriptor",async()=>{const a=recoveryAdapter({reserved:{id:"reserved",name:"remote",mimeType:FOLDER,parents:["other"],trashed:false,appProperties:prov()},parent:{id:"other",name:"elsewhere",mimeType:FOLDER,parents:["content"],trashed:false,appProperties:prov()}});const r=await a.observeFolderCreateRecovery(descriptor("empty/remote","parent"));assert.equal(r.status,"folder");if(r.status==="folder"){assert.equal(r.parentRemoteObjectId,"other");assert.equal(r.targetPath,"elsewhere/remote");}});
test("workstream A v1.2 recovery: wrong structural path is reported as actually observed",async()=>{const a=recoveryAdapter({reserved:{id:"reserved",name:"wrong",mimeType:FOLDER,parents:["parent"],trashed:false,appProperties:prov()}});const r=await a.observeFolderCreateRecovery(descriptor());assert.equal(r.status,"folder");if(r.status==="folder")assert.equal(r.targetPath,"empty/wrong");});
test("workstream A v1.2 recovery: absent reserved id plus independent occupant returns occupied",async()=>{const a=recoveryAdapter({reservedFailure:"not-found",targetChildren:[{id:"other",name:"remote",mimeType:FOLDER,parents:["parent"],trashed:false,appProperties:prov()}]});const r=await a.observeFolderCreateRecovery(descriptor());assert.equal(r.status,"occupied");if(r.status==="occupied")assert.equal(r.remoteObjectId,"other");});
test("workstream A v1.2 recovery: absence requires reserved-id absence and authoritatively clear target",async()=>{const a=recoveryAdapter({reservedFailure:"not-found",targetChildren:[]});const r=await a.observeFolderCreateRecovery(descriptor());assert.deepEqual(r,{status:"authoritative-absent",reservedRemoteObjectId:"reserved"});});
test("workstream A v1.2 recovery: duplicate structural target is unobservable",async()=>{const a=recoveryAdapter({reservedFailure:"not-found",targetChildren:[{id:"one",name:"remote",mimeType:FOLDER,parents:["parent"],trashed:false},{id:"two",name:"remote",mimeType:FOLDER,parents:["parent"],trashed:false}]});const r=await a.observeFolderCreateRecovery(descriptor());assert.equal(r.status,"unobservable");});
test("workstream A v1.2 recovery: duplicate parent path is unobservable",async()=>{const a=recoveryAdapter({reservedFailure:"not-found",duplicateParent:true,targetChildren:[]});const r=await a.observeFolderCreateRecovery(descriptor());assert.equal(r.status,"unobservable");});
test("workstream A v1.2 recovery: incomplete network/auth observation stays unobservable",async()=>{const a=recoveryAdapter({reservedFailure:"transient-failure"});const r=await a.observeFolderCreateRecovery(descriptor());assert.equal(r.status,"unobservable");});
test("workstream A v1.2 recovery: cancellation stays unobservable and performs no mutation",async()=>{const counter={value:0};const a=recoveryAdapter({mutationCounter:counter});const r=await a.observeFolderCreateRecovery(descriptor(),cancelledSignal());assert.equal(r.status,"unobservable");assert.equal(counter.value,0);});
test("workstream A v1.2 recovery: descriptor facts alone cannot manufacture observation",async()=>{const a=recoveryAdapter({reservedFailure:"transient-failure"});const d=descriptor("INTENDED/Path","intended-parent");const r=await a.observeFolderCreateRecovery(d);assert.deepEqual(r,{status:"unobservable",reason:"reserved-object-absence-unproven:transient-failure"});});

test("workstream A changes: reliable page distinguishes intermediate and terminal tokens without PATCH side effects",async()=>{let page=0;let patches=0;const a=adapter(async(url,init)=>{if(init?.method==="PATCH")patches++;const u=decodeURIComponent(url);const c=common(url);if(c)return c;if(u.includes("/files/content?"))return ok(content());if(u.includes("/changes?")){page++;return page===1?ok({changes:[{fileId:"f1",file:{id:"f1",name:"one.md",mimeType:"text/plain",parents:["content"],size:"1",version:"1"}}],nextPageToken:"p2"}):ok({changes:[{fileId:"f2",removed:true}],newStartPageToken:"terminal"});}throw new Error(u);});const first=await a.readChangePage(identity,cur("start"));assert.equal(first.ok,true);if(first.ok){assert.equal(first.value.kind,"intermediate");if(first.value.kind==="intermediate")assert.equal(first.value.nextPageToken,"p2");const second=await a.readChangePage(identity,first.value.kind==="intermediate"?first.value.nextPageToken:cur("bad"));assert.equal(second.ok,true);if(second.ok){assert.equal(second.value.kind,"terminal");assert.equal(second.value.changes[0].kind,"removed");}}assert.equal(patches,0);});

test("workstream A changes: malformed Drive token combination fails conservatively",async()=>{const a=adapter(async url=>{const u=decodeURIComponent(url);const c=common(url);if(c)return c;if(u.includes("/changes?"))return ok({changes:[],nextPageToken:"n",newStartPageToken:"t"});throw new Error(u);});const r=await a.readChangePage(identity,cur("start"));assert.equal(r.ok,false);if(!r.ok)assert.equal(r.signal.kind,"recovery-required");});

test("workstream A observation: reconciliation of legacy unstamped objects never PATCHes provenance",async()=>{let patches=0;const a=adapter(async(url,init)=>{if(init?.method==="PATCH")patches++;const u=decodeURIComponent(url);const c=common(url);if(c)return c;if(u.includes("'content' in parents")&&!u.includes("name="))return ok({files:[{id:"legacy",name:"legacy.md",mimeType:"text/plain",parents:["content"],size:"1",version:"1"}]});if(u.includes("'config' in parents"))return ok({files:[]});if(u.includes("brainManagedRootId"))return ok({files:[]});throw new Error(u);});const r=await a.listForReconciliation(ro("root"));assert.equal(r.ok,true);assert.equal(patches,0);});

test("workstream A create: file identity is pre-reserved and a lost create response reconciles same ID",async()=>{const proof:CanonicalFileContentProof={algorithm:"sha256",hash:ch("sha256:"+"a".repeat(64)),sizeBytes:3};let candidateExists=false;let metadataBody="";const a=adapter(async(url,init)=>{const u=decodeURIComponent(url);const c=common(url);if(c)return c;if(u.includes("/files/generateIds"))return ok({ids:["reserved-file"]});if(u.includes("/files/reserved-file?"))return candidateExists?ok({id:"reserved-file",name:"note.md",mimeType:"application/octet-stream",parents:["content"],size:"3",sha256Checksum:"a".repeat(64),version:"1",appProperties:prov()}):fail("not-found");if(u.includes("brainSyncRole' and value='brain-sync-root"))return ok({files:[root()]});if(u.startsWith("https://www.googleapis.com/upload/")){metadataBody=String(init?.body);candidateExists=true;return fail("transient-failure","lost-response");}throw new Error(u);});const reserved=await a.reserveFileCreateIdentity(identity,intent("create"),vp("note.md"),proof);assert.equal(reserved.ok,true);if(!reserved.ok)return;const source:BinaryContentSource={sizeBytes:3,async *openChunks(){yield new Uint8Array([1,2,3]);}};const outcome=await a.createReserved(reserved.value,source);assert.equal(outcome.status,"verified-effect");assert.match(metadataBody,/reserved-file/);});

test("workstream A update: immutable candidate preserves predecessor and verifies candidate",async()=>{const proof:CanonicalFileContentProof={algorithm:"sha256",hash:ch("sha256:"+"b".repeat(64)),sizeBytes:3};let candidateExists=false;const updateIdentity:Extract<RemoteMutationIdentity,{kind:"existing-file-content-update"}>={kind:"existing-file-content-update",intentId:intent("update"),remoteObjectId:ro("old"),expectedRevision:rev("7"),path:vp("note.md"),updateProtocol:"immutable-candidate-preservation",candidateRemoteObjectId:ro("candidate"),intendedContent:proof,identityAuthority:{generation:generation("g"),status:"unique",path:vp("note.md"),remoteObjectId:ro("old")}};const a=adapter(async(url,init)=>{const u=decodeURIComponent(url);const c=common(url);if(c)return c;if(u.includes("/files/old?"))return ok({id:"old",name:"note.md",mimeType:"text/plain",parents:["content"],size:"3",sha256Checksum:"c".repeat(64),version:"7",appProperties:prov()});if(u.includes("/files/candidate?"))return candidateExists?ok({id:"candidate",name:"note.md",mimeType:"application/octet-stream",parents:["content"],size:"3",sha256Checksum:"b".repeat(64),version:"1",appProperties:prov()}):fail("not-found");if(u.includes("/files/content?"))return ok(content());if(u.includes("'content' in parents")&&u.includes("name='note.md'"))return ok({files:[{id:"old",name:"note.md",mimeType:"text/plain",parents:["content"],size:"3",version:"7",appProperties:prov()},{id:"candidate",name:"note.md",mimeType:"text/plain",parents:["content"],size:"3",version:"1",appProperties:prov()}]});if(u.startsWith("https://www.googleapis.com/upload/")){candidateExists=true;return fail("transient-failure","lost-response");}throw new Error(`${init?.method??"GET"} ${u}`);});const source:BinaryContentSource={sizeBytes:3,async *openChunks(){yield new Uint8Array([4,5,6]);}};const outcome=await a.updateExisting(updateIdentity,source);assert.equal(outcome.status,"verified-effect");if(outcome.status==="verified-effect"&&outcome.applicationProof.kind==="immutable-candidate-preservation")assert.ok(outcome.applicationProof.preservedRemoteObjectIds.includes(ro("old")));});
