import assert from "node:assert/strict";
import test from "node:test";
import type { ContentEvidence, ManagedRemoteIdentity, PathSnapshot, RemoteObjectId, VaultPath, VersionReference } from "../src/contracts";
import { contractId } from "../src/contracts";
import { DeterministicSynchronizationPlanner } from "../src/core/planner";
import { ThreeWayConflictResolver } from "../src/core/conflict-resolver";
import { IntegratedProductController } from "../src/product/product-controller";
import { ProductSynchronizationExecutor } from "../src/product/production-executor";
import { BoundedAuditHistory, MemoryAuditPersistence } from "../src/product/audit-history";
import { ProductSnapshotAssembler } from "../src/product/snapshot-assembler";
import { MemoryTextVersionPersistence, ProductTextVersionStore } from "../src/product/text-version-store";
import { CONFIG_REMOTE_NAMESPACE, ProductPathScope, ScopedLocalVault } from "../src/product/path-scope";
import { MemoryStateByteStorage, PersistentSynchronizationStateStore, createInitialTrustedState } from "../src/state/persistent-state-store";
import { sha256Text } from "../src/util/sha256";

const id=<T extends string>(v:string)=>contractId<T>(v);
const vp=(v:string)=>id<"VaultPath">(v) as VaultPath;
const vault=id<"VaultIdentity">("vault:reject2"),device=id<"DeviceIdentity">("device:reject2"),root=id<"RemoteObjectId">("root") as RemoteObjectId;
const managed:ManagedRemoteIdentity={rootId:root,vaultIdentity:vault,protocolVersion:id<"ProtocolVersion">("1")};
const canonical=(s:string):ContentEvidence=>({hash:sha256Text(s),sizeBytes:new TextEncoder().encode(s).byteLength});
const resolver=new ThreeWayConflictResolver({readText:async()=>undefined});
function localOnly(path:VaultPath):PathSnapshot{return{path,local:{status:"present",side:"local",path,entityKind:"file",content:canonical("safe"),stability:"stable",observationToken:id<"ObservationToken">(`tok:${String(path)}`)},remote:{status:"absent",side:"remote",path},base:{status:"uninitialized"},remoteEnumeration:{status:"complete"},identity:{status:"unambiguous"}};}
function unreadable(path:VaultPath):PathSnapshot{return{path,local:{status:"unreadable",side:"local",path,reason:"cannot-read"},remote:{status:"absent",side:"remote",path},base:{status:"uninitialized"},remoteEnumeration:{status:"complete"},identity:{status:"unambiguous"}};}

test("C1 all path-local blocked-unsafe work remains attention-only rather than a global block",async()=>{const plan=await new DeterministicSynchronizationPlanner(resolver).plan({snapshots:[unreadable(vp("bad.md"))],state:{status:"uninitialized"}});assert.equal(plan.executionDisposition,"requires-user-approval");assert.equal(plan.globalExecutionGate,"none");});
test("C1 recovery-required plan is blocked",async()=>{const plan=await new DeterministicSynchronizationPlanner(resolver).plan({snapshots:[],state:{status:"recovery-required",reason:"integrity-check-failed"}});assert.equal(plan.executionDisposition,"blocked");});
test("C1 mixed safe plus blocked path is reviewable",async()=>{const plan=await new DeterministicSynchronizationPlanner(resolver).plan({snapshots:[localOnly(vp("safe.md")),unreadable(vp("bad.md"))],state:{status:"uninitialized"}});assert.equal(plan.executionDisposition,"requires-user-approval");assert.equal(plan.operations.some(o=>o.kind==="upload-create"),true);assert.equal(plan.operations.some(o=>o.kind==="blocked-unsafe"),true);});
test("C1 automatic run executes the independently safe subset of a mixed attention plan",async()=>{const state=new PersistentSynchronizationStateStore(new MemoryStateByteStorage());let calls=0;const assembly={input:{snapshots:[localOnly(vp("safe.md")),unreadable(vp("bad.md"))],state:{status:"uninitialized" as const}},managedRemote:managed,remoteEnumeration:{status:"complete" as const},mode:"incremental" as const};const controller=new IntegratedProductController({vaultIdentity:vault,deviceIdentity:device,stateContext:{expectation:"new-installation"},stateStore:state,snapshotAssembler:{assemble:async()=>assembly} as never,executor:{validatePreconditions:async()=>({status:"valid" as const}),execute:async(operation:any)=>{calls++;return{status:"durable-verified-success" as const,receipt:{operationId:operation.operationId,durable:true as const,integrityVerified:true as const,verificationEvidenceRef:"fixture"}};},failureScope:()=>"global" as const} as never,conflictResolver:resolver,plannerForTrigger:trigger=>new DeterministicSynchronizationPlanner(resolver,undefined,{trigger}),leasePort:{tryAcquire:async()=>({release:async()=>undefined})} as never,audit:new BoundedAuditHistory(new MemoryAuditPersistence(),20),holderId:"auto"});await controller.runAutomatic("periodic");assert.equal(calls,1);assert.equal(controller.currentSurface().status.kind,"attention-required");});

test("C3 retained text requires canonical SHA-256 and rejects corruption",async()=>{const p=new MemoryTextVersionPersistence(),path=vp("note.md"),version:VersionReference={path,entityKind:"file",content:canonical("good")};await p.put(`hash:${String(version.content!.hash)}`,"good");const store=new ProductTextVersionStore(p,{} as never,{} as never);assert.equal(await store.retainedText(version),"good");await p.put(`hash:${String(version.content!.hash)}`,"bad");assert.equal(await store.retainedText(version),undefined);});
test("C3 revision-only text is rejected and yields unresolved conflict",async()=>{const store=new ProductTextVersionStore(new MemoryTextVersionPersistence(),{} as never,{} as never),path=vp("note.md");const base:VersionReference={path,entityKind:"file",content:{revision:"1"}},local:VersionReference={path,entityKind:"file",content:{revision:"2"}},remote:VersionReference={path,entityKind:"file",content:{revision:"3"},remoteObjectId:id<"RemoteObjectId">("remote")};assert.equal(await store.persistText(base,"base"),false);assert.equal((await new ThreeWayConflictResolver(store,store).assess(path,base,local,remote)).kind,"unresolved-text");});

test("C4 reserved ordinary vault content cannot alias real configuration",async()=>{const prefix=vp(CONFIG_REMOTE_NAMESPACE),logical=vp(`${CONFIG_REMOTE_NAMESPACE}/app.json`);const inner={enumerate:async()=>({entries:[],completeness:{status:"complete" as const}}),observe:async(path:VaultPath)=>String(path)===CONFIG_REMOTE_NAMESPACE?({status:"present" as const,side:"local" as const,path:prefix,entityKind:"folder" as const,stability:"stable" as const}):({status:"absent" as const,side:"local" as const,path}),readFile:async()=>{throw new Error("wrong-content");}} as never;const local=new ScopedLocalVault(inner,new ProductPathScope(vp(".obsidian"),()=>({userExclusionPatterns:[]})));assert.equal((await local.observe(logical)).status,"unknown");await assert.rejects(()=>local.readFile(logical),/collides with reserved/);});

test("C5 scope reconcile requirement forces full assembly",async()=>{const state=new PersistentSynchronizationStateStore(new MemoryStateByteStorage());await state.saveTrusted({...createInitialTrustedState({stateRevision:id<"StateRevision">("state:0"),vaultIdentity:vault,deviceIdentity:device}),changeCursor:id<"ChangeCursor">("old")});let full=0,changes=0;const assembler=new ProductSnapshotAssembler({enumerate:async()=>({entries:[],completeness:{status:"complete" as const}})} as never,{validateManagedRoot:async()=>({ok:true as const,value:{status:"valid" as const,identity:managed}}),getStartCursor:async()=>({ok:true as const,value:id<"ChangeCursor">("new")}),listForReconciliation:async()=>{full++;return{ok:true as const,value:{entries:[],completeness:{status:"complete" as const}}};},readChanges:async()=>{changes++;throw new Error("incremental forbidden");}} as never,state,{expectation:"existing-pairing",expectedVaultIdentity:vault,expectedDeviceIdentity:device},async()=>managed,()=>true,()=>true);assert.equal((await assembler.assemble(true)).mode,"full");assert.equal(full,1);assert.equal(changes,0);});

test("C6 assembler consumes ID-only removed event after restart",async()=>{const path=vp("gone.md"),remoteId=id<"RemoteObjectId">("gone"),state=new PersistentSynchronizationStateStore(new MemoryStateByteStorage());await state.saveTrusted({...createInitialTrustedState({stateRevision:id<"StateRevision">("state:0"),vaultIdentity:vault,deviceIdentity:device}),changeCursor:id<"ChangeCursor">("old"),base:[{path,entityKind:"file",localExisted:true,remoteExisted:true,content:canonical("base"),remoteObjectId:remoteId}],remoteMappings:[{path,entityKind:"file",remoteObjectId:remoteId}]});const assembled=await new ProductSnapshotAssembler({enumerate:async()=>({entries:[{status:"present" as const,side:"local" as const,path,entityKind:"file" as const,content:canonical("base"),stability:"stable" as const,observationToken:id<"ObservationToken">("tok")}],completeness:{status:"complete" as const}})} as never,{validateManagedRoot:async()=>({ok:true as const,value:{status:"valid" as const,identity:managed}}),readChanges:async()=>({ok:true as const,value:{changes:[{kind:"removed" as const,remoteObjectId:remoteId}],nextCursor:id<"ChangeCursor">("next"),completeness:{status:"complete" as const}}})} as never,state,{expectation:"existing-pairing",expectedVaultIdentity:vault,expectedDeviceIdentity:device},async()=>managed).assemble(true);assert.equal(assembled.input.snapshots[0].remote.status,"absent");assert.equal((await new DeterministicSynchronizationPlanner(resolver).plan(assembled.input)).operations[0].kind,"trash-local");});

test("C7 executor preserves authentication-required classification",async()=>{const path=vp("note.md"),remoteId=id<"RemoteObjectId">("remote"),executor=new ProductSynchronizationExecutor({observe:async()=>({status:"present" as const,side:"local" as const,path,entityKind:"file" as const,content:canonical("local"),stability:"stable" as const})} as never,{observe:async()=>({ok:false as const,signal:{kind:"authentication-required" as const,detail:"google-account-changed-repair-required"}})} as never,{} as never,{expectation:"existing-pairing"},()=>({managedRemote:managed,remoteEnumerationComplete:true}));const result=await executor.validatePreconditions({operationId:id<"OperationId">("op"),kind:"upload-update",path,remoteObjectId:remoteId,destructive:false,preconditions:[{kind:"remote-object",remoteObjectId:remoteId}],reasons:[]});assert.equal(result.status,"blocked");if(result.status==="blocked")assert.equal(result.reason,"authentication-required:google-account-changed-repair-required");});
