import assert from "node:assert/strict";
import test from "node:test";
import type { ContentEvidence, ManagedRemoteIdentity, PathSnapshot, VaultPath } from "../src/contracts";
import { contractId } from "../src/contracts";
import { DeterministicSynchronizationPlanner } from "../src/core/planner";
import { ThreeWayConflictResolver } from "../src/core/conflict-resolver";
import { BoundedAuditHistory, MemoryAuditPersistence } from "../src/product/audit-history";
import { IntegratedProductController } from "../src/product/product-controller";
import type { AssembledPlanningInput } from "../src/product/snapshot-assembler";
import { MemoryStateByteStorage, PersistentSynchronizationStateStore, createInitialTrustedState } from "../src/state/persistent-state-store";
import { sha256Text } from "../src/util/sha256";
const id=<T extends string>(v:string)=>contractId<T>(v),vp=(v:string)=>id<"VaultPath">(v) as VaultPath;
const vault=id<"VaultIdentity">("vault:auth"),device=id<"DeviceIdentity">("device:auth"),managed:ManagedRemoteIdentity={rootId:id<"RemoteObjectId">("root"),vaultIdentity:vault,protocolVersion:id<"ProtocolVersion">("1")};
const context={expectation:"existing-pairing" as const,expectedVaultIdentity:vault,expectedDeviceIdentity:device};
const ev=(s:string):ContentEvidence=>({hash:sha256Text(s),sizeBytes:s.length});
const resolver=new ThreeWayConflictResolver({readText:async()=>undefined});
function snapshot(name:string):PathSnapshot{const path=vp(name);return{path,local:{status:"present",side:"local",path,entityKind:"file",content:ev(name),stability:"stable",observationToken:id<"ObservationToken">(`tok:${name}`)},remote:{status:"absent",side:"remote",path},base:{status:"trusted"},remoteEnumeration:{status:"complete"},identity:{status:"unambiguous"}};}
async function run(detail:string){const store=new PersistentSynchronizationStateStore(new MemoryStateByteStorage());await store.saveTrusted({...createInitialTrustedState({stateRevision:id<"StateRevision">("state:0"),vaultIdentity:vault,deviceIdentity:device}),changeCursor:id<"ChangeCursor">("cursor:old")});const loaded=await store.load(context);const assembly:AssembledPlanningInput={input:{snapshots:[snapshot("a.md"),snapshot("b.md")],state:loaded},managedRemote:managed,remoteEnumeration:{status:"complete"},mode:"full",nextCursor:id<"ChangeCursor">("cursor:new")};let validations=0,mutations=0;const executor={validatePreconditions:async()=>{validations++;return{status:"blocked" as const,reason:`authentication-required:${detail}`};},execute:async()=>{mutations++;throw new Error("mutation must not start");},failureScope:()=>"global" as const} as never;const controller=new IntegratedProductController({vaultIdentity:vault,deviceIdentity:device,stateContext:context,stateStore:store,snapshotAssembler:{assembleFull:async()=>assembly} as never,executor,conflictResolver:resolver,plannerForTrigger:trigger=>new DeterministicSynchronizationPlanner(resolver,undefined,{trigger}),leasePort:{tryAcquire:async()=>({release:async()=>undefined})} as never,audit:new BoundedAuditHistory(new MemoryAuditPersistence(),50),holderId:`auth:${detail}`});const plan=await controller.previewManual();assert.ok(plan);const result=await controller.request({kind:"execute-plan",planId:plan!.planId});return{controller,result,store,validations,mutations};}
test("Phase5 scenario 38 auth revoked after planning surfaces authentication-required and stops run",async()=>{const h=await run("authorization-revoked");assert.equal(h.result.status,"rejected");assert.deepEqual(h.controller.currentSurface().status,{kind:"authentication-required",reason:"authorization-revoked"});assert.equal(h.validations,1);assert.equal(h.mutations,0);const loaded=await h.store.load(context);assert.equal(loaded.status,"trusted");if(loaded.status==="trusted")assert.equal(String(loaded.state.changeCursor),"cursor:old");});
test("Phase5 scenario 39 wrong account during execution preserves re-pair reason",async()=>{const h=await run("google-account-changed-repair-required");assert.deepEqual(h.controller.currentSurface().status,{kind:"authentication-required",reason:"google-account-changed-repair-required"});assert.equal(h.validations,1);assert.equal(h.mutations,0);});
