import assert from "node:assert/strict";
import test from "node:test";
import type { BinaryContentSource, ContentEvidence, ManagedRemoteIdentity, ObservationToken, PathSnapshot, RemoteObjectId, StateLoadContext, TrustedSynchronizationState, VaultPath } from "../src/contracts";
import { contractId } from "../src/contracts";
import { ThreeWayConflictResolver } from "../src/core/conflict-resolver";
import { InMemoryRunLeasePort } from "../src/core/run-coordinator";
import { DeterministicSynchronizationPlanner } from "../src/core/planner";
import { ProductionSynchronizationPlanner } from "../src/core/production-planner";
import { BoundedAuditHistory, MemoryAuditPersistence } from "../src/product/audit-history";
import { IntegratedProductController } from "../src/product/product-controller";
import { ProductSynchronizationExecutor } from "../src/product/production-executor";
import { ProductSnapshotAssembler } from "../src/product/snapshot-assembler";
import { createInitialTrustedState, MemoryStateByteStorage, PersistentSynchronizationStateStore } from "../src/state/persistent-state-store";
import { sha256Text } from "../src/util/sha256";

const id=<T extends string>(v:string)=>contractId<T>(v),vp=(v:string)=>id<"VaultPath">(v) as VaultPath,rid=(v:string)=>id<"RemoteObjectId">(v) as RemoteObjectId,cur=(v:string)=>id<"ChangeCursor">(v);
const ev=(t:string):ContentEvidence=>({hash:sha256Text(t),sizeBytes:new TextEncoder().encode(t).byteLength});
const src=(t:string):BinaryContentSource=>({sizeBytes:new TextEncoder().encode(t).byteLength,async *openChunks(){yield new TextEncoder().encode(t);}});
const vault=id<"VaultIdentity">("vault:g2:coord"),device=id<"DeviceIdentity">("device:g2:coord"),identity:ManagedRemoteIdentity={rootId:rid("root:g2:coord"),vaultIdentity:vault,protocolVersion:id<"ProtocolVersion">("1")};
const existing:StateLoadContext={expectation:"existing-pairing",expectedVaultIdentity:vault,expectedDeviceIdentity:device};
function baseState(path:VaultPath,r:RemoteObjectId,text:string,stale=false):TrustedSynchronizationState{const s=createInitialTrustedState({stateRevision:id<"StateRevision">("state:0"),vaultIdentity:vault,deviceIdentity:device});return{...s,base:[{path,entityKind:"file",localExisted:true,remoteExisted:true,content:ev(text),remoteObjectId:r}],remoteMappings:[{path,entityKind:"file",remoteObjectId:r}],changeCursor:cur("cursor:old"),knownDevices:[{deviceId:device,stale}]};}
function conflicts(){return new ThreeWayConflictResolver({readText:async()=>undefined});}
async function makeController(local:any,drive:any,store:PersistentSynchronizationStateStore,assembler:any,context:StateLoadContext=existing,lease:any=new InMemoryRunLeasePort(),holder="g2-coord"){const cfx=conflicts();let controller!:IntegratedProductController;const executor=new ProductSynchronizationExecutor(local,drive,store,context,()=>controller.currentRunEvidence());controller=new IntegratedProductController({vaultIdentity:vault,deviceIdentity:device,stateContext:context,stateStore:store,snapshotAssembler:assembler,executor,conflictResolver:cfx,plannerForTrigger:t=>new ProductionSynchronizationPlanner(new DeterministicSynchronizationPlanner(cfx,undefined,{trigger:t})),leasePort:lease,audit:new BoundedAuditHistory(new MemoryAuditPersistence(),100),holderId:holder});return controller;}

test("G2 scenario 20 invalid Changes cursor falls back to safe full Phase5 reconciliation and commits a fresh cursor",async()=>{const p=vp("cursor.md"),r=rid("rid:cursor"),store=new PersistentSynchronizationStateStore(new MemoryStateByteStorage());await store.saveTrusted(baseState(p,r,"same"));let changes=0,full=0;const local={enumerate:async()=>({entries:[{status:"present" as const,side:"local" as const,path:p,entityKind:"file" as const,content:ev("same"),stability:"stable" as const,observationToken:id<"ObservationToken">("tok")}],completeness:{status:"complete" as const}}),observe:async()=>({status:"present" as const,side:"local" as const,path:p,entityKind:"file" as const,content:ev("same"),stability:"stable" as const,observationToken:id<"ObservationToken">("tok")})} as never;const drive={validateManagedRoot:async()=>({ok:true as const,value:{status:"valid" as const,identity}}),readChanges:async()=>{changes++;return{ok:false as const,signal:{kind:"not-found" as const}};},getStartCursor:async()=>({ok:true as const,value:cur("cursor:fresh")}),listForReconciliation:async()=>{full++;return{ok:true as const,value:{entries:[{path:p,entityKind:"file" as const,remoteObjectId:r,content:ev("same"),trashed:false}],completeness:{status:"complete" as const}}};}} as never;const assembler=new ProductSnapshotAssembler(local,drive,store,existing,async()=>identity),controller=await makeController(local,drive,store,assembler);await controller.runAutomatic("periodic");assert.equal(changes,1);assert.equal(full,1);const loaded=await store.load(existing);assert.equal(loaded.status,"trusted");if(loaded.status==="trusted")assert.equal(loaded.state.changeCursor,cur("cursor:fresh"));});

test("G2 scenarios 21 and 22 incomplete remote or local observation cannot become deletion authority in Phase5 planning",async()=>{const p=vp("uncertain.md"),r=rid("rid:uncertain");for(const mode of ["remote-partial","local-partial"] as const){const store=new PersistentSynchronizationStateStore(new MemoryStateByteStorage());await store.saveTrusted(baseState(p,r,"base"));let trash=0;const local={enumerate:async()=>mode==="local-partial"?{entries:[],completeness:{status:"partial" as const,reason:"unreadable subtree"}}:{entries:[{status:"present" as const,side:"local" as const,path:p,entityKind:"file" as const,content:ev("base"),stability:"stable" as const}],completeness:{status:"complete" as const}},trash:async()=>{trash++;}} as never;const drive={validateManagedRoot:async()=>({ok:true as const,value:{status:"valid" as const,identity}}),getStartCursor:async()=>({ok:true as const,value:cur("cursor:new")}),listForReconciliation:async()=>({ok:true as const,value:{entries:[],completeness:mode==="remote-partial"?{status:"partial" as const,reason:"page incomplete"}:{status:"complete" as const}}}),trash:async()=>{trash++;return{ok:true as const,value:undefined};}} as never;const assembler=new ProductSnapshotAssembler(local,drive,store,existing,async()=>identity),controller=await makeController(local,drive,store,assembler);const plan=await controller.previewManual();assert.ok(plan);assert.equal(plan.operations.some(o=>o.kind==="blocked-unsafe"),true);assert.equal(trash,0);}});

test("G2 scenario 23 stale current device cannot authorize destructive propagation through production controller planning",async()=>{const p=vp("stale.md"),r=rid("rid:stale"),store=new PersistentSynchronizationStateStore(new MemoryStateByteStorage());await store.saveTrusted(baseState(p,r,"base",true));let trash=0;const local={enumerate:async()=>({entries:[],completeness:{status:"complete" as const}})} as never,drive={validateManagedRoot:async()=>({ok:true as const,value:{status:"valid" as const,identity}}),getStartCursor:async()=>({ok:true as const,value:cur("fresh")}),listForReconciliation:async()=>({ok:true as const,value:{entries:[{path:p,entityKind:"file" as const,remoteObjectId:r,content:ev("base"),trashed:false}],completeness:{status:"complete" as const}}}),trash:async()=>{trash++;return{ok:true as const,value:undefined};}} as never;const controller=await makeController(local,drive,store,new ProductSnapshotAssembler(local,drive,store,existing,async()=>identity)),plan=await controller.previewManual();assert.ok(plan);assert.equal(plan.executionDisposition,"blocked");assert.equal(plan.operations.some(o=>o.kind==="blocked-unsafe"),true);assert.equal(trash,0);});

test("G2 scenario 40 missing expected managed root blocks Phase5 before planning or mutation",async()=>{const context:StateLoadContext={expectation:"new-installation"},store=new PersistentSynchronizationStateStore(new MemoryStateByteStorage());let mutation=0;const local={enumerate:async()=>({entries:[],completeness:{status:"complete" as const}})} as never,drive={validateManagedRoot:async()=>({ok:true as const,value:{status:"missing-root" as const}}),create:async()=>{mutation++;throw new Error("no mutation");}} as never,assembler=new ProductSnapshotAssembler(local,drive,store,context,async()=>identity),controller=await makeController(local,drive,store,assembler,context);assert.equal(await controller.previewManual(),undefined);assert.equal(controller.currentSurface().status.kind,"recovery-required");assert.equal(mutation,0);});

function localOnly(path:VaultPath,text:string):PathSnapshot{return{path,local:{status:"present",side:"local",path,entityKind:"file",content:ev(text),stability:"stable",observationToken:id<"ObservationToken">(`tok:${String(path)}`)},remote:{status:"absent",side:"remote",path},base:{status:"uninitialized"},remoteEnumeration:{status:"complete"},identity:{status:"unambiguous"}};}
async function coordinationHarness(paths:readonly string[],lease:any=new InMemoryRunLeasePort(),holder="coord"){const context:StateLoadContext={expectation:"new-installation",expectedVaultIdentity:vault,expectedDeviceIdentity:device},store=new PersistentSynchronizationStateStore(new MemoryStateByteStorage()),files=new Map(paths.map(p=>[p,p])),remote=new Map<string,{r:RemoteObjectId;e:ContentEvidence}>();let active=0,max=0,holdPath:string|undefined,release:(()=>void)|undefined;const calls:string[]=[],started=new Map<string,Promise<void>>(),resolveStarted=new Map<string,()=>void>();for(const p of paths)started.set(p,new Promise<void>(r=>resolveStarted.set(p,r)));const local={observe:async(p:VaultPath)=>({status:"present" as const,side:"local" as const,path:p,entityKind:"file" as const,content:ev(files.get(String(p))!),stability:"stable" as const,observationToken:id<"ObservationToken">(`tok:${String(p)}`)}),readFile:async(p:VaultPath)=>({content:src(files.get(String(p))!),evidence:ev(files.get(String(p))!),stability:"stable" as const,observationToken:id<"ObservationToken">(`tok:${String(p)}`)}),validatePath:async(p:VaultPath)=>({status:"compatible" as const,normalizedComparisonPath:String(p)})} as never;const drive={observe:async(_r:RemoteObjectId,p:VaultPath)=>{const x=remote.get(String(p));return x?{ok:true as const,value:{status:"present" as const,side:"remote" as const,path:p,entityKind:"file" as const,remoteObjectId:x.r,content:x.e,stability:"stable" as const}}:{ok:true as const,value:{status:"absent" as const,side:"remote" as const,path:p}};},create:async(_r:RemoteObjectId,q:{path:VaultPath;expectedEvidence?:ContentEvidence})=>{active++;max=Math.max(max,active);calls.push(String(q.path));resolveStarted.get(String(q.path))?.();if(holdPath===String(q.path))await new Promise<void>(r=>release=r);const r=rid(`r:${String(q.path)}`),e=q.expectedEvidence??ev(String(q.path));remote.set(String(q.path),{r,e});active--;return{ok:true as const,value:{remoteObjectId:r,path:q.path,evidence:e}};}} as never;const initial={input:{snapshots:paths.map(p=>localOnly(vp(p),p)),state:{status:"uninitialized" as const}},managedRemote:identity,remoteEnumeration:{status:"complete" as const},nextCursor:cur("cursor:coord"),mode:"full" as const};const assemble=async()=>{if(remote.size!==paths.length)return initial;const loaded=await store.load(context);return{input:{snapshots:[],state:loaded},managedRemote:identity,remoteEnumeration:{status:"complete" as const},nextCursor:cur("cursor:coord:later"),mode:"full" as const};};const controller=await makeController(local,drive,store,{assemble,assembleFull:assemble} as never,context,lease,holder);return{controller,store,calls,started,hold:(p:string)=>{holdPath=p;},release:()=>release?.(),max:()=>max,context};}

test("G2 scenario 27 cancellation stops future operations and leaves cursor unadvanced",async()=>{const h=await coordinationHarness(["a.md","b.md"]);h.hold("a.md");const run=h.controller.runAutomatic("periodic");await h.started.get("a.md");await h.controller.request({kind:"cancel-active-sync"});h.release();await run;assert.deepEqual(h.calls,["a.md"]);const loaded=await h.store.load(h.context);assert.equal(loaded.status,"trusted");if(loaded.status==="trusted")assert.equal(loaded.state.changeCursor,undefined);});

test("G2 scenario 28 pause blocks product-controller synchronization until resume",async()=>{const h=await coordinationHarness(["pause.md"]);await h.controller.request({kind:"pause"});await h.controller.runAutomatic("periodic");assert.deepEqual(h.calls,[]);assert.equal(h.controller.currentSurface().status.kind,"paused");await h.controller.request({kind:"resume"});await h.controller.runAutomatic("periodic");assert.deepEqual(h.calls,["pause.md"]);});

test("G2 scenario 29 same-runtime product synchronization runs serialize rather than overlap",async()=>{const h=await coordinationHarness(["serial.md"]);h.hold("serial.md");const first=h.controller.runAutomatic("periodic");await h.started.get("serial.md");const second=h.controller.runAutomatic("periodic");await Promise.resolve();assert.equal(h.max(),1);h.release();await Promise.all([first,second]);await new Promise(r=>globalThis.setTimeout(r,5));assert.equal(h.max(),1);});

test("G2 scenario 30 two real controller runs sharing production lease cannot mutate concurrently",async()=>{const lease=new InMemoryRunLeasePort(),a=await coordinationHarness(["lease-a.md"],lease,"a"),b=await coordinationHarness(["lease-b.md"],lease,"b");a.hold("lease-a.md");const first=a.controller.runAutomatic("periodic");await a.started.get("lease-a.md");await b.controller.runAutomatic("periodic");assert.deepEqual(b.calls,[]);a.release();await first;assert.equal(a.max(),1);});
