import assert from "node:assert/strict";
import test from "node:test";
import type { ConflictAssessment, ContentEvidence, ManagedRemoteIdentity, PathSnapshot, PlannedOperation, VaultPath, VersionReference } from "../src/contracts";
import { contractId } from "../src/contracts";
import { DeterministicSynchronizationPlanner } from "../src/core/planner";
import { ThreeWayConflictResolver } from "../src/core/conflict-resolver";
import { BoundedAuditHistory, MemoryAuditPersistence } from "../src/product/audit-history";
import { IntegratedProductController } from "../src/product/product-controller";
import type { AssembledPlanningInput } from "../src/product/snapshot-assembler";
import { MemoryStateByteStorage, PersistentSynchronizationStateStore, createInitialTrustedState } from "../src/state/persistent-state-store";
import { sha256Text } from "../src/util/sha256";
const id=<T extends string>(v:string)=>contractId<T>(v),vp=(v:string)=>id<"VaultPath">(v) as VaultPath;
const vault=id<"VaultIdentity">("vault:recovery"),device=id<"DeviceIdentity">("device:recovery"),managed:ManagedRemoteIdentity={rootId:id<"RemoteObjectId">("root"),vaultIdentity:vault,protocolVersion:id<"ProtocolVersion">("1")};
const context={expectation:"existing-pairing" as const,expectedVaultIdentity:vault,expectedDeviceIdentity:device};
const ev=(s:string):ContentEvidence=>({hash:sha256Text(s),sizeBytes:s.length}),resolver=new ThreeWayConflictResolver({readText:async()=>undefined});
function conflictSnapshot(name:string):PathSnapshot{const path=vp(name);return{path,local:{status:"present",side:"local",path,entityKind:"file",content:ev(`local-${name}`),stability:"stable",observationToken:id<"ObservationToken">(`tok-${name}`)},remote:{status:"present",side:"remote",path,entityKind:"file",content:{...ev(`remote-${name}`),revision:`rev-${name}`},remoteObjectId:id<"RemoteObjectId">(`rid-${name}`),stability:"stable"},base:{status:"uninitialized"},remoteEnumeration:{status:"complete"},identity:{status:"unambiguous"}};}
function recoveryAssembly(snapshots:readonly PathSnapshot[]):AssembledPlanningInput{return{input:{snapshots,state:{status:"uninitialized"}},managedRemote:managed,remoteEnumeration:{status:"complete"},mode:"full",reconstruction:true,nextCursor:id<"ChangeCursor">("cursor:recovery")};}
function fakeExecutor(){return{validatePreconditions:async()=>({status:"valid" as const}),execute:async(operation:PlannedOperation)=>({status:"durable-verified-success" as const,receipt:{operationId:operation.operationId,durable:true,integrityVerified:true,evidence:operation.contentVersion?.content,verificationEvidenceRef:`fake:${String(operation.operationId)}`}}),versionStillCurrent:async()=>true,currentLocalVersion:async(path:VaultPath):Promise<VersionReference>=>({path,entityKind:"file",content:ev("manual"),observationToken:id<"ObservationToken">("manual-token")}),localPathState:async()=>"absent" as const,failureScope:()=>"global" as const};}
async function seededStore(){const store=new PersistentSynchronizationStateStore(new MemoryStateByteStorage());await store.saveTrusted(createInitialTrustedState({stateRevision:id<"StateRevision">("state:0"),vaultIdentity:vault,deviceIdentity:device}));return store;}

test("C2 recovery conflict mutation remains blocked until fresh reconstruction establishes durable authority",async()=>{const store=await seededStore();let recovery=true;const gateEvents:boolean[]=[];let snapshots:readonly PathSnapshot[]=[conflictSnapshot("one.bin"),conflictSnapshot("two.bin")];const controller=new IntegratedProductController({vaultIdentity:vault,deviceIdentity:device,stateContext:context,stateStore:store,snapshotAssembler:{assembleRecovery:async()=>recoveryAssembly(snapshots)} as never,executor:fakeExecutor() as never,conflictResolver:resolver,plannerForTrigger:trigger=>new DeterministicSynchronizationPlanner(resolver,undefined,{trigger}),leasePort:{tryAcquire:async()=>({release:async()=>undefined})} as never,audit:new BoundedAuditHistory(new MemoryAuditPersistence(),100),holderId:"recovery-conflicts",recoveryActive:()=>recovery,onRecoveryGateChanged:async active=>{gateEvents.push(active);recovery=active;}});await controller.previewVerifyReconcile();assert.equal(controller.currentSurface().conflicts.length,2);const conflicts=controller.currentSurface().conflicts as Exclude<ConflictAssessment,{kind:"none"}>[];for(const conflict of conflicts){assert.ok("conflictId" in conflict);if("conflictId" in conflict)assert.equal((await controller.request({kind:"resolve-conflict",conflictId:conflict.conflictId,resolution:{kind:"keep-local"}})).status,"rejected");assert.equal(recovery,true);assert.equal(gateEvents.includes(false),false);assert.equal(controller.currentSurface().status.kind,"recovery-required");}snapshots=[];const fresh=await controller.previewVerifyReconcile();assert.ok(fresh);assert.equal((await controller.request({kind:"execute-plan",planId:fresh!.planId})).status,"accepted");assert.equal(recovery,false);assert.deepEqual(gateEvents,[false]);const loaded=await store.load(context);assert.equal(loaded.status,"trusted");if(loaded.status==="trusted")assert.equal(String(loaded.state.changeCursor),"cursor:recovery");assert.equal((await controller.readAuditHistory()).some(r=>r.event==="recovery-completed"),true);});

test("C2 cursorless recovery-derived conflict subplan has no recovery-completion authority",async()=>{const store=await seededStore();let recovery=true,cleared=0;const controller=new IntegratedProductController({vaultIdentity:vault,deviceIdentity:device,stateContext:context,stateStore:store,snapshotAssembler:{assembleRecovery:async()=>recoveryAssembly([conflictSnapshot("only.bin")])} as never,executor:fakeExecutor() as never,conflictResolver:resolver,plannerForTrigger:trigger=>new DeterministicSynchronizationPlanner(resolver,undefined,{trigger}),leasePort:{tryAcquire:async()=>({release:async()=>undefined})} as never,audit:new BoundedAuditHistory(new MemoryAuditPersistence(),50),holderId:"cursorless",recoveryActive:()=>recovery,onRecoveryGateChanged:async active=>{if(!active)cleared++;recovery=active;}});await controller.previewVerifyReconcile();const conflict=controller.currentSurface().conflicts[0] as Exclude<ConflictAssessment,{kind:"none"}>;assert.ok("conflictId" in conflict);if("conflictId" in conflict)await controller.request({kind:"resolve-conflict",conflictId:conflict.conflictId,resolution:{kind:"keep-local"}});assert.equal(cleared,0);assert.equal(recovery,true);assert.equal(controller.currentSurface().status.kind,"recovery-required");});

test("C5 partial full run cannot signal scope-reconcile completion",async()=>{const store=await seededStore();let completed=0;const original=conflictSnapshot("blocked.bin");const blocked:PathSnapshot={...original,local:{status:"unreadable",side:"local",path:original.path,reason:"bad"}};const loaded=await store.load(context);const assembly:AssembledPlanningInput={input:{snapshots:[blocked],state:loaded},managedRemote:managed,remoteEnumeration:{status:"complete"},mode:"full",nextCursor:id<"ChangeCursor">("candidate")};const controller=new IntegratedProductController({vaultIdentity:vault,deviceIdentity:device,stateContext:context,stateStore:store,snapshotAssembler:{assembleFull:async()=>assembly} as never,executor:fakeExecutor() as never,conflictResolver:resolver,plannerForTrigger:trigger=>new DeterministicSynchronizationPlanner(resolver,undefined,{trigger}),leasePort:{tryAcquire:async()=>({release:async()=>undefined})} as never,audit:new BoundedAuditHistory(new MemoryAuditPersistence(),50),holderId:"scope-partial",onFullReconciliationCompleted:async()=>{completed++;}});const plan=await controller.previewVerifyReconcile();assert.ok(plan);assert.equal((await controller.request({kind:"execute-plan",planId:plan!.planId})).status,"accepted");assert.equal(completed,0);});

test("C5 only complete full run with candidate cursor signals scope-reconcile completion",async()=>{const store=await seededStore();let completed=0;const loaded=await store.load(context);const assembly:AssembledPlanningInput={input:{snapshots:[],state:loaded},managedRemote:managed,remoteEnumeration:{status:"complete"},mode:"full",nextCursor:id<"ChangeCursor">("scope-new")};const controller=new IntegratedProductController({vaultIdentity:vault,deviceIdentity:device,stateContext:context,stateStore:store,snapshotAssembler:{assembleFull:async()=>assembly} as never,executor:fakeExecutor() as never,conflictResolver:resolver,plannerForTrigger:trigger=>new DeterministicSynchronizationPlanner(resolver,undefined,{trigger}),leasePort:{tryAcquire:async()=>({release:async()=>undefined})} as never,audit:new BoundedAuditHistory(new MemoryAuditPersistence(),50),holderId:"scope-complete",onFullReconciliationCompleted:async()=>{completed++;}});const plan=await controller.previewVerifyReconcile();assert.ok(plan);assert.equal((await controller.request({kind:"execute-plan",planId:plan!.planId})).status,"accepted");assert.equal(completed,1);const after=await store.load(context);assert.equal(after.status,"trusted");if(after.status==="trusted")assert.equal(String(after.state.changeCursor),"scope-new");});