import assert from "node:assert/strict";
import test from "node:test";
import type { BinaryContentSource, ContentEvidence, ManagedRemoteIdentity, ObservationToken, RemoteObjectId, StateLoadContext, VaultPath } from "../src/contracts";
import { contractId } from "../src/contracts";
import { ThreeWayConflictResolver } from "../src/core/conflict-resolver";
import { DeterministicSynchronizationPlanner } from "../src/core/planner";
import { ProductionSynchronizationPlanner } from "../src/core/production-planner";
import { InMemoryRunLeasePort } from "../src/core/run-coordinator";
import { BoundedAuditHistory, MemoryAuditPersistence } from "../src/product/audit-history";
import { MeaningfulNotificationFilter } from "../src/product/notification-policy";
import { CONFIG_REMOTE_NAMESPACE, ProductPathScope, ScopedLocalVault } from "../src/product/path-scope";
import { DEFAULT_SETTINGS, type BrainSyncSettings } from "../src/product/plugin-data";
import { IntegratedProductController } from "../src/product/product-controller";
import { ProductSynchronizationExecutor } from "../src/product/production-executor";
import { Phase5ProductRuntime } from "../src/product/runtime";
import { ProductSnapshotAssembler } from "../src/product/snapshot-assembler";
import { MemoryStateByteStorage, PersistentSynchronizationStateStore } from "../src/state/persistent-state-store";
import { sha256Text } from "../src/util/sha256";

const id=<T extends string>(v:string)=>contractId<T>(v),vp=(v:string)=>id<"VaultPath">(v) as VaultPath,rid=(v:string)=>id<"RemoteObjectId">(v) as RemoteObjectId;
const ev=(t:string):ContentEvidence=>({hash:sha256Text(t),sizeBytes:new TextEncoder().encode(t).byteLength});
const src=(t:string):BinaryContentSource=>({sizeBytes:new TextEncoder().encode(t).byteLength,async *openChunks(){yield new TextEncoder().encode(t);}});
async function txt(s:BinaryContentSource){let out="";const d=new TextDecoder();for await(const c of s.openChunks())out+=d.decode(c,{stream:true});return out+d.decode();}
const vault=id<"VaultIdentity">("vault:g2:surface"),device=id<"DeviceIdentity">("device:g2:surface"),root=rid("root:g2:surface"),identity:ManagedRemoteIdentity={rootId:root,vaultIdentity:vault,protocolVersion:id<"ProtocolVersion">("1")};

function runtimeHarness(){let settings:BrainSyncSettings={...DEFAULT_SETTINGS,oauthClientId:"client",oauthRedirectUri:"https://example.test/callback",vaultIdentity:String(vault),deviceIdentity:String(device),remoteRootId:String(root)};const saved:BrainSyncSettings[]=[];const notifications:string[]=[];const host={app:{} as never,plugin:{} as never,settings:()=>settings,data:{} as never,saveSettings:async(next:BrainSyncSettings)=>{settings=next;saved.push(next);},notify:(message:string)=>notifications.push(message)};const runtime=new Phase5ProductRuntime(host);return{runtime,host,saved,notifications,settings:()=>settings};}

test("G2 scenario 6 Phase5 runtime pairing consumes validated managed-root identity and refuses invalid pairing",async()=>{for(const valid of [true,false]){const h=runtimeHarness(),calls:string[]=[];const boundary={drive:{pairManagedRoot:async(r:RemoteObjectId,v:any)=>{calls.push(`${String(r)}:${String(v)}`);return{ok:true as const,value:valid?{status:"valid" as const,identity}:{status:"identity-mismatch" as const}};}},oauth:{}};Object.assign(h.runtime as unknown as Record<string,unknown>,{boundary});let initialized=0;(h.runtime as unknown as {initialize:()=>Promise<void>}).initialize=async()=>{initialized++;};if(valid){const paired=await h.runtime.pairManagedRemote();assert.equal(paired.rootId,root);assert.equal(initialized,1);assert.equal(h.settings().firstSyncCompleted,false);assert.equal(h.settings().localChangeEnabled,false);}else{await assert.rejects(()=>h.runtime.pairManagedRemote(),/Pairing refused/);assert.equal(initialized,0);}assert.deepEqual(calls,[`${String(root)}:${String(vault)}`]);}});

test("G2 scenario 50 Phase5 deauthorization and disposal clear authority without local or Drive deletion",async()=>{const h=runtimeHarness();let clear=0,stop=0,cancel=0,dispose=0,localTrash=0,remoteTrash=0;const boundary={oauth:{clearTokens:()=>{clear++;}},drive:{trash:async()=>{remoteTrash++;return{ok:true as const,value:undefined};}}};const scheduler={stop:()=>{stop++;}};const controller={request:async(action:{kind:string})=>{if(action.kind==="cancel-active-sync")cancel++;return{status:"accepted" as const};}};const local={dispose:()=>{dispose++;},trash:async()=>{localTrash++;}};Object.assign(h.runtime as unknown as Record<string,unknown>,{boundary,scheduler,controller,local});await h.runtime.deauthorize();assert.equal(clear,1);assert.equal(stop,1);assert.equal(cancel,1);assert.equal(dispose,1);assert.equal(localTrash,0);assert.equal(remoteTrash,0);assert.equal(h.settings().remoteRootId,"");assert.equal(h.settings().startupResumeEnabled,false);assert.equal(h.settings().localChangeEnabled,false);assert.equal(h.settings().periodicEnabled,false);});

async function makeController(options:{local:any;drive:any;pathIncluded?:(p:VaultPath)=>boolean;auditLimit?:number}){const store=new PersistentSynchronizationStateStore(new MemoryStateByteStorage()),context:StateLoadContext={expectation:"new-installation",expectedVaultIdentity:vault,expectedDeviceIdentity:device},assembler=new ProductSnapshotAssembler(options.local,options.drive,store,context,async()=>identity,options.pathIncluded);const conflicts=new ThreeWayConflictResolver({readText:async()=>undefined});const audit=new BoundedAuditHistory(new MemoryAuditPersistence(),options.auditLimit??50);let controller!:IntegratedProductController;const executor=new ProductSynchronizationExecutor(options.local,options.drive,store,context,()=>controller.currentRunEvidence());controller=new IntegratedProductController({vaultIdentity:vault,deviceIdentity:device,stateContext:context,stateStore:store,snapshotAssembler:assembler,executor,conflictResolver:conflicts,plannerForTrigger:t=>new ProductionSynchronizationPlanner(new DeterministicSynchronizationPlanner(conflicts,undefined,{trigger:t})),leasePort:new InMemoryRunLeasePort(),audit,holderId:"g2-surface"});return{controller,store,context,audit};}

test("G2 scenarios 44 and 45 repeated path-local failure stays isolated while safe work commits and real activity produces bounded audit records",async()=>{const bad=vp("bad.md"),good=vp("good.md"),badId=rid("rid:bad"),goodId=rid("rid:good"),remote=new Map([[String(bad),{path:bad,id:badId,text:"bad"}],[String(good),{path:good,id:goodId,text:"good"}]]),local=new Map<string,string>();let badAttempts=0;const localPort={enumerate:async()=>({entries:[...local].map(([p,t])=>({status:"present" as const,side:"local" as const,path:vp(p),entityKind:"file" as const,content:ev(t),stability:"stable" as const,observationToken:id<"ObservationToken">(`tok:${p}`)})),completeness:{status:"complete" as const}}),observe:async(p:VaultPath)=>local.has(String(p))?{status:"present" as const,side:"local" as const,path:p,entityKind:"file" as const,content:ev(local.get(String(p))!),stability:"stable" as const,observationToken:id<"ObservationToken">(`tok:${String(p)}`)}:{status:"absent" as const,side:"local" as const,path:p},createFile:async(p:VaultPath,c:BinaryContentSource)=>{if(p===bad){badAttempts++;throw new Error("Blocked local path (invalid-name): bad.md");}local.set(String(p),await txt(c));return{path:p,evidence:ev(local.get(String(p))!)};},validatePath:async(p:VaultPath)=>({status:"compatible" as const,normalizedComparisonPath:String(p)})} as never;const drive={validateManagedRoot:async()=>({ok:true as const,value:{status:"valid" as const,identity}}),getStartCursor:async()=>({ok:true as const,value:id<"ChangeCursor">("cursor:surface")}),listForReconciliation:async()=>({ok:true as const,value:{entries:[...remote.values()].map(x=>({path:x.path,entityKind:"file" as const,remoteObjectId:x.id,content:ev(x.text),trashed:false})),completeness:{status:"complete" as const}}}),download:async(r:RemoteObjectId)=>{const x=[...remote.values()].find(v=>v.id===r)!;return{ok:true as const,value:{remoteObjectId:r,content:src(x.text),evidence:ev(x.text)}};},observe:async(_r:RemoteObjectId,p:VaultPath)=>{const x=remote.get(String(p));return x?{ok:true as const,value:{status:"present" as const,side:"remote" as const,path:p,entityKind:"file" as const,remoteObjectId:x.id,content:ev(x.text),stability:"stable" as const}}:{ok:true as const,value:{status:"absent" as const,side:"remote" as const,path:p}};}} as never;const h=await makeController({local:localPort,drive,auditLimit:4});for(let i=0;i<2;i++){const p=await h.controller.previewManual();assert.ok(p);const result=await h.controller.request({kind:"execute-plan",planId:p.planId});assert.equal(result.status,"accepted");}assert.equal(badAttempts,2);assert.equal(local.get("good.md"),"good");const records=await h.controller.readAuditHistory();assert.equal(records.length<=4,true);assert.equal(records.some(r=>r.event==="operation-completed"&&String(r.path)==="good.md"),true);assert.equal(records.some(r=>r.event==="operation-failed"&&String(r.path)==="bad.md"),true);assert.equal(JSON.stringify(records).includes("good\""),false);});

test("G2 scenario 47 production surface listener passes only material conditions through notification delivery filter",async()=>{const notices:string[]=[];const filter=new MeaningfulNotificationFilter();const local={enumerate:async()=>({entries:[],completeness:{status:"complete" as const}})} as never;let valid=true;const drive={validateManagedRoot:async()=>valid?{ok:true as const,value:{status:"valid" as const,identity}}:{ok:true as const,value:{status:"missing-root" as const}},getStartCursor:async()=>({ok:true as const,value:id<"ChangeCursor">("c")}),listForReconciliation:async()=>({ok:true as const,value:{entries:[],completeness:{status:"complete" as const}}})} as never;const h=await makeController({local,drive});h.controller.onSurface(surface=>{const message=filter.next(surface);if(message)notices.push(message);});const plan=await h.controller.previewManual();assert.ok(plan);assert.deepEqual(notices,[]);valid=false;await h.controller.previewManual();assert.equal(notices.length,1);assert.match(notices[0],/recovery/i);});

test("G2 scenario 48 allowlisted portable configuration synchronizes through reserved domain while device-local and unknown configuration stay excluded",async()=>{const config=vp(".obsidian"),physical=new Map<string,string>([[".obsidian/app.json",'{"theme":"dark"}'],[".obsidian/workspace.json","device"],[".obsidian/plugins/example/data.json","unknown"]]),created:string[]=[];const raw={enumerate:async()=>({entries:[],completeness:{status:"complete" as const}}),observe:async(p:VaultPath)=>{const t=physical.get(String(p));return t===undefined?{status:"absent" as const,side:"local" as const,path:p}:{status:"present" as const,side:"local" as const,path:p,entityKind:"file" as const,content:ev(t),stability:"stable" as const,observationToken:id<"ObservationToken">(`tok:${String(p)}`)};},readFile:async(p:VaultPath)=>({content:src(physical.get(String(p))!),evidence:ev(physical.get(String(p))!),stability:"stable" as const}),validatePath:async(p:VaultPath)=>({status:"compatible" as const,normalizedComparisonPath:String(p)}),activeConfigurationDirectory:async()=>config,onChange:()=>()=>undefined,onLifecycle:()=>()=>undefined} as never;const scope=new ProductPathScope(config,()=>({userExclusionPatterns:[]})),local=new ScopedLocalVault(raw,scope);const remote=new Map<string,{id:RemoteObjectId;e:ContentEvidence}>(),drive={validateManagedRoot:async()=>({ok:true as const,value:{status:"valid" as const,identity}}),getStartCursor:async()=>({ok:true as const,value:id<"ChangeCursor">("config-cursor")}),listForReconciliation:async()=>({ok:true as const,value:{entries:[],completeness:{status:"complete" as const}}}),observe:async(_r:RemoteObjectId,p:VaultPath)=>{const x=remote.get(String(p));return x?{ok:true as const,value:{status:"present" as const,side:"remote" as const,path:p,entityKind:"file" as const,remoteObjectId:x.id,content:x.e,stability:"stable" as const}}:{ok:true as const,value:{status:"absent" as const,side:"remote" as const,path:p}};},create:async(_r:RemoteObjectId,q:{path:VaultPath;content?:BinaryContentSource;expectedEvidence?:ContentEvidence})=>{created.push(String(q.path));const i=rid(`rid:${String(q.path)}`),e=q.expectedEvidence!;if(q.content)await txt(q.content);remote.set(String(q.path),{id:i,e});return{ok:true as const,value:{remoteObjectId:i,path:q.path,evidence:e}};}} as never;const h=await makeController({local:local as never,drive,pathIncluded:p=>scope.isManagedLogical(p)});const p=await h.controller.previewManual();assert.ok(p);assert.equal((await h.controller.request({kind:"execute-plan",planId:p.planId})).status,"accepted");assert.deepEqual(created,[`${CONFIG_REMOTE_NAMESPACE}/app.json`]);assert.equal(created.some(x=>/workspace|plugins\/example/.test(x)),false);});
