import type { CheckpointId, ConflictId, OperationId, PlanId, VaultPath } from "./common";
import type { ConflictAssessment, ConflictResolution } from "./conflict";
import type { SynchronizationPlan } from "./plan";
export type SynchronizationStatus = { readonly kind: "idle-ready" } | { readonly kind: "planning"; readonly trigger: string } | { readonly kind: "syncing"; readonly planId: PlanId } | { readonly kind: "offline-deferred" | "authentication-required"; readonly reason?: string } | { readonly kind: "paused" } | { readonly kind: "conflict-present"; readonly conflictCount: number } | { readonly kind: "destructive-plan-blocked"; readonly planId: PlanId } | { readonly kind: "recovery-required"; readonly reason: string } | { readonly kind: "error"; readonly code: string; readonly message: string };
export type AuditEventKind = "plan-created" | "operation-completed" | "operation-failed" | "conflict-created" | "conflict-resolved" | "trash-action" | "recovery-entered" | "recovery-completed" | "destructive-plan-approved" | "sync-cancelled";
/** Privacy-safe metadata only: no note/binary payload field exists. */
export interface AuditRecord { readonly id: string; readonly event: AuditEventKind; readonly advisoryAtMs: number; readonly path?: VaultPath; readonly operationId?: OperationId; readonly planId?: PlanId; readonly reasonCode?: string; readonly side?: "local" | "remote"; readonly count?: number; }
export interface ProductSurfaceState { readonly status: SynchronizationStatus; readonly planPreview?: SynchronizationPlan; readonly conflicts: readonly ConflictAssessment[]; readonly recoveryReason?: string; }
export type UserAction = { readonly kind: "execute-plan"; readonly planId: PlanId } | { readonly kind: "resolve-conflict"; readonly conflictId: ConflictId; readonly resolution: ConflictResolution } | { readonly kind: "approve-destructive-plan"; readonly planId: PlanId; readonly recoveryCheckpointId: CheckpointId } | { readonly kind: "pause" | "resume" | "verify-reconcile-vault" | "cancel-active-sync" };
export type UserActionResult = { readonly status: "accepted" } | { readonly status: "rejected"; readonly reason: string };
export interface ProductControlPort { currentSurface(): ProductSurfaceState; request(action: UserAction): Promise<UserActionResult>; onSurface(listener: (surface: ProductSurfaceState) => void): () => void; readAuditHistory(): Promise<readonly AuditRecord[]>; }
